package com.helpdesk.ticket.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Ticket Entity - Support ticket
 */
@Entity
@Table(name = "tickets")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Ticket {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable, externally-shown identifier (e.g. "TKT-000142").
     * Generated by the service layer after the row is persisted (so it can
     * incorporate the auto-incremented {@link #id}). Unique and indexed for
     * lookup. Nullable so existing rows from earlier schema versions stay
     * valid until backfilled.
     */
    @Column(name = "ticket_number", unique = true, length = 32)
    private String ticketNumber;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, columnDefinition = "VARCHAR(32)")
    private TicketPriority priority;

    @Column(nullable = false)
    private String category;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, columnDefinition = "VARCHAR(32)")
    private TicketStatus status;

    @Column(nullable = false)
    private Long createdBy;

    @Column
    private Long assignedTo;

    /**
     * Optional asset this ticket relates to (e.g. a broken laptop).
     * Just an ID — looking up the asset crosses the asset-service boundary.
     */
    @Column(name = "linked_asset_id")
    private Long linkedAssetId;

    // ----- Location of the failing device / requester ------------------------
    // All optional and free-text — different organisations track different
    // levels of detail. Captured at ticket creation so technicians don't have
    // to ask the user "where is it?" before dispatching.

    @Column(name = "building", length = 100)
    private String building;

    @Column(name = "location_department", length = 100)
    private String locationDepartment;

    @Column(name = "room_number", length = 50)
    private String roomNumber;

    @Column(name = "location_notes", length = 500)
    private String locationNotes;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /** Set when status transitions to RESOLVED. Distinct from {@link #closedAt}. */
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    @Column
    private LocalDateTime closedAt;

    public enum TicketPriority {
        LOW, MEDIUM, HIGH, CRITICAL
    }

    /**
     * HESK-aligned status workflow.
     *
     * Lifecycle (typical):
     *   NEW → ASSIGNED → IN_PROGRESS → (WAITING_FOR_USER | WAITING_FOR_VENDOR | ON_HOLD)*
     *                  → RESOLVED → CLOSED
     *   CLOSED/RESOLVED → REOPENED → IN_PROGRESS
     *
     * Existing rows with the old subset (OPEN, IN_PROGRESS, RESOLVED, CLOSED)
     * remain valid because those values are still members of this enum.
     */
    public enum TicketStatus {
        NEW,
        OPEN,
        ASSIGNED,
        IN_PROGRESS,
        WAITING_FOR_USER,
        WAITING_FOR_VENDOR,
        ON_HOLD,
        RESOLVED,
        CLOSED,
        REOPENED,
        /** User-cancelled; excluded from technician queue and open-ticket counts. */
        CANCELLED
    }
}
